tranding_mas=[
    {
        "color":"color1",
        "img":"trending_bottom1.jpg",
        "color_text":"Lifestyple"
    },
    {
        "color":"color2",
        "img":"trending_bottom2.jpg",
        "color_text":"Sports"
    },
    {
        "color":"color3",
        "img":"trending_bottom3.jpg",
        "color_text":"Travels"
    }
]

riht_content=[
    {
        "img":"right1.jpg",
        "color":"color1"
    },
    {
        "img":"right2.jpg",
        "color":"color3"
    },
    {
        "img":"right3.jpg",
        "color":"color2"
    },
    {
        "img":"right4.jpg",
        "color":"color4"
    },
    {
        "img":"right5.jpg",
        "color":"color1"
    }

]

weak_mas=[
    {
        "img":"weeklyNews2.jpg"
    },
    {
        "img":"weeklyNews1.jpg"
    },
    {
        "img":"weeklyNews3.jpg"
    },
    {
        "img":"weeklyNews1.jpg"
    }
]

nav_button=[
    {
        "id":"nav-home-tab",
        "href":"#nav-home",
        "controls":"nav-home",
        "text":"All"
    },
    {
        "id":"nav-profile-tab",
        "href":"#nav-profile",
        "controls":"nav-profile",
        "text":"Lifestyle"
    },
    {
        "id":"nav-contact-tab",
        "href":"#nav-contact",
        "controls":"nav-contact",
        "text":"Travel"
    },
    {
        "id":"nav-last-tab",
        "href":"#nav-last",
        "controls":"nav-contact",
        "text":"Fashion"
    },
    {
        "id":"nav-Sports",
        "href":"#nav-nav-Sport",
        "controls":"nav-contact",
        "text":"Sports"
    },
    {
        "id":"nav-technology",
        "href":"#nav-techno",
        "controls":"nav-contact",
        "text":"Technology"
    }
]

nav_card=[
    {
       "id":"nav-home",
        "mas":["whatNews3.jpg",
            
                "whatNews1.jpg"
            ,
            
                "whatNews2.jpg"
            ,
                "whatNews3.jpg"
            
        ]
    }
]